FROM openjdk:11-jdk-slim
ENV PORT 8081
EXPOSE 8081

COPY *.jar app.jar
CMD ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Dspring.profiles.active=dev", "-jar", "app.jar"]